CREATE DATABASE FUNDACAO;
USE FUNDACAO;

CREATE TABLE FUNCIONARIO(
	ID_FUNC INT NOT NULL AUTO_INCREMENT,
    NOME_FUNC VARCHAR(255) NOT NULL,
    EMAIL_FUNC VARCHAR(255) NOT NULL,
    SENHA_FUNC VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID_FUNC)
);

CREATE TABLE CIDADE(
	ID_CID INT NOT NULL AUTO_INCREMENT,
    NOME_CID VARCHAR(255) NOT NULL,
    CEP_CID VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID_CID)
);



CREATE TABLE VITIMA(
	ID_VITI INT NOT NULL AUTO_INCREMENT,
    NOME_VITI VARCHAR(255) NOT NULL,
    CIDADE_VITI INT NOT NULL,
    PRIMARY KEY(ID_VITI),
    FOREIGN KEY(CIDADE_VITI) REFERENCES CIDADE(ID_CID)
);

INSERT INTO CIDADE(NOME_CID, CEP_CID)
VALUES("Erechim", "99700-000");

INSERT INTO FUNCIONARIO(NOME_FUNC, EMAIL_FUNC, SENHA_FUNC)
VALUES("adilar", "adilarpamonha@png.com", "123");

SELECT * FROM FUNCIONARIO;

