openapi: 3.0.3
info:
  version: "1.0"
  title: Documentação da API Manoel Gome
  description: "Essa API lista todos os endpoints possveis para a aplicação"
servers:
  - url: http://localhost:6969
paths:
  /funcionario:
    post:
      summary: Criar um novo funcionario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Funcionario'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Funcionario'
  /funcionario/{email}/{senha}:
    get:
      summary: Selecionar um funcionario
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
        - name: senha
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Funcionario'
    put:
      summary: Atualizar um funcionario
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
        - name: senha
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Funcionario'
        
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Funcionario'
    delete:
      summary: Deletar um funcionario
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
        - name: senha
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
  /vitimas:
    get:
      summary: Selecionar todas as vitimas para a lista
      responses:
        200:
          description: OK
  /vitima:
    post:
      summary: Crar uma nova vitima
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vitima'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vitima'

components:
  schemas:
    Funcionario:
      type: object
      properties:
        email:
          type: string
        nome:
          type: string
        senha:
          type: string
      required:
        - email
        - nome
        - senha

    Vitima:
      type: object
      properties:
        nome:
          type: string
        cidade:
          type: string
      required:
        - nome
        - cidade
